config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  root 'main#index'
  resources :conversations, :users, :messages
end

app/views/layouts/_flash_message.slim
- flash.each do |type, message|
  - if message.present?
    div class=("uk-notify-message alert #{bootstrap_class_for(type)} alert-dismissible")
      button.close[data-dismiss='alert']
        | ×
      div
        = message

app/views/layouts/_footer.slim
.container-fluid.container-footer
  footer.container-fixed
    | my-app © 2017

app/views/layouts/_head.slim
title = content_for?(:title) ? yield(:title) : 'my-app'
meta name='keywords' content='my-app'
= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
= csrf_meta_tags
= action_cable_meta_tag

app/views/layouts/_header.slim
.container-fluid.container-header
  header
    .row
      .col-sm-6.offset-md-3
        = link_to root_path, class: 'home-text float-left' do
          | Главная
        = link_to conversations_path, class: 'message-text float-left' do
          | Беседы
        - if user_signed_in?
          = link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'login-text sign-in float-right'
        - else
          = link_to 'Войти', '#loginModal', class: 'login-text not-sign-in float-right', 'data-toggle' => 'modal', 'data-keyboard' => 'false', 'data-backdrop' => 'static'
- unless current_user
  = render 'layouts/login'
  = render 'layouts/sign_up'

app/views/layouts/_login.slim
.modal.fade id='loginModal' tabindex='-1' role='dialog' aria-labelledby='loginModal' aria-hidden='true'
  .modal-dialog.modal-dialog-center role='document'
    .modal-content
      .modal-header
        h5.modal-title id='loginModalLabel' Войдите
        button.close type='button' data-dismiss='modal' aria-label='Close'
          span aria-hidden='true'
            == ("&times")
      .modal-body
        = form_for(resource, as: resource_name, url: session_path(resource_name), remote: true, data: {type: 'json'}, html: {id: 'login_modal'}) do |f|

          .form-group
            = f.text_field :login, autofocus: true, placeholder: 'Login or Email', class: 'form-control'
          .form-group
            = f.password_field :password, autocomplete: 'off', placeholder: 'Password', class: 'form-control', id: 'login_password'
          - if devise_mapping.rememberable?
            .form-group
              = f.check_box :remember_me
              = f.label :remember_me, class: 'pl-2'

          .form-group
            = f.submit 'Log in', class: 'btn btn-lg btn-success btn-block'
      .modal-footer.justify-content-start
        = link_to "Sign up", '#signUpModal', 'data-toggle' => 'modal', 'data-keyboard' => 'false', 'data-backdrop' => 'static', 'data-dismiss' => 'modal', class: 'justify-content-start'
        = link_to "Forgot your password?", new_password_path(resource_name), class: 'ml-auto p-2'

app/views/layouts/_sign_up.slim
.modal.fade id='signUpModal' tabindex='-1' role='dialog' aria-labelledby='signUpModal' aria-hidden='true'
  .modal-dialog.modal-dialog-center role='document'
    .modal-content
      .modal-header
        h5.modal-title id='SignUpModalLabel' Зарегистрируйтесь
        button.close type='button' data-dismiss='modal' aria-label='Close'
          span aria-hidden='true'
            == ("&times")
      .modal-body
        = form_for(resource, as: resource_name, url: registration_path(resource_name), remote: true, data: {type: 'json'}, html: {id: 'new_user_modal'}) do |f|

          .form-group
            = f.text_field :username, autofocus: true, placeholder: 'Login', class: 'form-control'
          .form-group
            = f.email_field :email, placeholder: 'Email', class: 'form-control'
          .form-group
            = f.password_field :password, autocomplete: 'off', placeholder: 'Password', class: 'form-control', id: 'sign_up_password'
            em.pl-1
              | (6 characters minimum)
          .form-group
            = f.password_field :password_confirmation, autocomplete: 'off', placeholder: 'Password Confirmation', class: 'form-control'

          .form-group
            = f.submit 'Sign up', class: 'btn btn-lg btn-primary btn-block'
      .modal-footer.justify-content-start
        = link_to 'Sign in', '#loginModal', 'data-toggle' => 'modal', 'data-keyboard' => 'false', 'data-backdrop' => 'static', 'data-dismiss' => 'modal', class: 'justify-content-start'
        = link_to "Forgot your password?", new_password_path(resource_name), class: 'ml-auto p-2'

app/views/layouts/application.slim
doctype html
html
  head
    - if content_for?(:head)
      = yield(:head)
    = render 'layouts/head'

  body
    .uk-notify.uk-notify-top-center
      = devise_error_messages!
      = render 'layouts/flash_message', flash: flash
    = render 'layouts/header'
    .container-fluid.container-main
      .container.container-fixed role='main'
        = yield

    = render 'layouts/footer'